language: 
  - cpp
compiler:
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-test-dev lcov
  - gem install coveralls-lcov
script: 
  - cd C/test && make coveralls
